[Window Options]
Tool Tips Font Face=Arial
Tool Tips Font Size=9
Show Splash Screen=False
Splash Screen File=OB_SPLASH
MDI Background Text=
MDI Scroll Bars=True
Show Unix Data=False
Grid Memory Buffer=20

[Message Log]
Topmost=True

[Message Box]
Title=
Always Override=False

[Remote]
System=
Protocol=APPC
OpSys=AS400
Program=YOBSYRPC
Library=PLEX
Job Description=PLEX/PLEX
Buffer Size=4
Data Conversion=1
Port=31000
UserId=
Password=
Code Page=10

[RemoteWinNT]
System=
OpSys=WINNT
Protocol=NTRPC
Program=PLEX_NT_DISPATCHER
Environment=
UseSecurity=0
SecurityLevel=1

[RemoteUnix]
System=
OpSys=HPUX
Protocol=TCPIP
Program=dispatch
Path=/usr/plex/bin/
Buffer Size=4
UserId=
Password=

[RemoteJava]
System=localhost
OpSys=JAVAVM
Protocol=JAVATCPIP
Port=1998
Environment=Default
Timeout=60

[International Settings]
Uppercase Input=False
Uppercase EBCDIC Input=True
COOL:Plex Language=esp
PNL directory path=.\Pnl

[Settings]
PreviewPages=2
DLL directory path=.\Dll

[ODBC Settings]
DSN=
Userid=
Password=
Database=
Errorlog=False
Fetch Type=
Default Connect=True

[Special Field Values]
Character High Value=z
Character Low Value=" " 
Character Empty Value=" " 
Date High Value=9999-12-31
Date Low Value=0001-01-01
Date Empty Value=0001-01-01
Time High Value=23:59:59
Time Low Value=00:00:00
Time Empty Value=00:00:00
Timestamp High Value=9999-12-31 23:59:59
Timestamp Low Value=0001-01-01 00:00:00
Timestamp Empty Value=0001-01-01 00:00:00

[ODBC-DBMS: Microsoft SQL Server]
Character High Value=
Character Low Value=
Character Empty Value=
Date High Value=
Date Low Value=1753-01-01
Date Empty Value=1753-01-01
Time High Value=
Time Low Value=
Time Empty Value=
Timestamp High Value=
Timestamp Low Value=1753-01-01 00:00:00
Timestamp Empty Value=1753-01-01 00:00:00

[DBMS: Sybase SQL Anywhere]
Character High Value=
Character Low Value=
Character Empty Value=
Date High Value=
Date Low Value=
Date Empty Value=
Time High Value=
Time Low Value=
Time Empty Value=
Timestamp High Value=
Timestamp Low Value=
Timestamp Empty Value=

[ODBC-DBMS: WATCOM SQL]
Character High Value=
Character Low Value=
Character Empty Value=
Date High Value=
Date Low Value=
Date Empty Value=
Time High Value=
Time Low Value=
Time Empty Value=
Timestamp High Value=
Timestamp Low Value=
Timestamp Empty Value=

[DBMS: Oracle]
Character High Value=
Character Low Value=
Character Empty Value=
Date High Value=
Date Low Value=
Date Empty Value=
Time High Value=
Time Low Value=
Time Empty Value=
Timestamp High Value=
Timestamp Low Value=
Timestamp Empty Value=

[ODBC-DBMS: Oracle7]
Character High Value=
Character Low Value=
Character Empty Value= 
Date High Value=
Date Low Value=
Date Empty Value=
Time High Value=
Time Low Value=
Time Empty Value=
Timestamp High Value=
Timestamp Low Value=
Timestamp Empty Value=

[ODBC-DBMS: Oracle8]
Character High Value=
Character Low Value=
Character Empty Value= 
Date High Value=
Date Low Value=
Date Empty Value=
Time High Value=
Time Low Value=
Time Empty Value=
Timestamp High Value=
Timestamp Low Value=
Timestamp Empty Value=

;[ODBC-DSN: Sample]
;Character High Value=
;Character Low Value= 
;Character Empty Value= 
;Date High Value=
;Date Low Value=
;Date Empty Value=
;Time High Value=
;Time Low Value=
;Time Empty Value=
;Timestamp High Value=
;Timestamp Low Value=
;Timestamp Empty Value=

[ODBC-DSN: Plex Tutorial.dsn]
Positioned Update=False	
Character High Value=
Character Low Value=
Character Empty Value=
Date High Value=
Date Low Value=
Date Empty Value=12-31-0000
Time High Value=
Time Low Value=
Time Empty Value=
Timestamp High Value=
Timestamp Low Value=
Timestamp Empty Value=

[Report]
Open=
Print=    
